CREATE TABLE ingrediente (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nome VARCHAR(255) NOT NULL,
                             descricao VARCHAR(255),
                             medida_Kg_ou_L VARCHAR(255) NOT NULL,
                             quantidade INT NOT NULL
);